baseURL = "https://xapi-project.github.io/new-docs/"
languageCode = 'en-us'
title = 'XAPI Toolstack Developer Documentation'
disablePathToLower = true
pygmentsCodeFences = true
assetsDir = "assets"

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant = "red"
alwaysopen = false
collapsibleMenu = true
